### ISSUE TITLE
COPERT v1 is not working

### ISSUE THREAD

**Issue by dpolitak** [Horizon-LEAD/lead-platform-doc#9]
screenshots below:
![Screenshot from 2023-03-27 19-00-36](https://user-images.githubusercontent.com/39014207/227997681-5ccbdb23-9a0d-43e0-a405-fdc4db415c4c.png)

![Screenshot from 2023-03-27 18-44-00](https://user-images.githubusercontent.com/39014207/227993561-a1da08af-366c-4398-afe1-354495409c3d.png)

**Comment by andalexo** [comment]
You placed the input on COPERT HOST API but did not save the value.
Therefore upon starting the simulation, the platform threw this error due to the missing input data.

This indicates a different issue though; that is that the message should be improved.

But since it has nothing to do with the actual model execution COPERT I am closing this issue.
